vars<-names(narrowData)
descr<-vars
descr<-gsub("^t", "\t\tTime Domain Signal of ", descr)
descr<-gsub("^f", "\t\tFrequency Domain Signal of ", descr)
descr<-gsub("Body", "Body ", descr)
descr<-gsub("Acc", "Acceleration ", descr)
descr<-gsub("Gravity", "Gravity ", descr)
descr<-gsub("Jerk", "Jerk ", descr)
descr<-gsub("Gyro", "Gyroscope ", descr)
descr<-gsub("Mag", "Magnitude ", descr)
descr<-gsub("mean\\(\\)", "Mean Value", descr)
descr<-gsub("std\\(\\)", "Standard Deviation", descr)
descr<-gsub("-X", " -X axis", descr)
descr<-gsub("-Y", " -Y axis", descr)
descr<-gsub("-Z", " -Z axis", descr)
vars<-paste(rep("*", 68), vars, sep=" ")
write.table(paste(vars, descr,sep=": "), "CodeBook.md", quote=FALSE, row.names=FALSE)